### ISSUE TITLE
Create first draft of design document

### ISSUE THREAD

**Issue by jaepark98** [cmsc22000-project-2018/spellcheck#3]
The spell checker tool must allow a user to open a text file, and to interactively correct any misspelled words. The spell checker must highlight in some way one misspelled word at a time, and suggest possible corrections to the user (the user can accept one of the corrections, leave the word as-is, or provide an alternate spelling). The spell checker must save the file with the corrections (or save it to an alternate file, if specified by the user)

When run in batch mode, the spell checker can operate in one of two ways: * It will take a text file and will replace all misspelled words with the best possible replacement. * It will take a text file containing a list of words, and will produce a list of all the misspelled words with the suggested corrections for each word.

**Comment by mpcsh** [comment]
I can't remember if we explicitly mentioned this in class, but the design doc will be done in the GitHub wiki. You should see the button for the wiki next to the pull requests and projects buttons.

**Comment by denizturkcapar** [comment]
I added the design doc yesterday to the GitHub wiki page

**Comment by mpcsh** [comment]
@denizturkcapar - I don't see the design doc, just the UML diagram. Are you sure you found the wiki?

**Comment by borjasotomayor** [comment]
The design doc is looking very promising. One way in which you may want to flesh out details is by providing a mock-up of the user experience. For example:

> In interactive mode, the user runs the spell-check command like this:
> 
```
./spell-check file.txt
```
> 
> Where file.txt is the file that is going to be spell-checked. Then,
> the program finds the first line with a misspelled word, and highlights
> that word:
> 
```
and then the fox jomped over the fens
                 ^^^^^^
```
>
> And presents possible alternatives as follows:
> 
> TO BE CONTINUED

This is a very useful exercise when fleshing out how exactly your application will behave (and, in turn, breaking down high-level requirements into more concrete tasks that need to be done)

You can then take specific parts of that interaction and produce either a UML sequence diagram or an informal sequence of function calls that are involved in a specific part of the interaction (e.g., something as seemingly simple as "find the first line with a misspelled word and highlight that word" will break down into a number of different function calls)

**Comment by firatciftci** [comment]
Added terminal recording videos to the design document.

**Comment by jaepark98** [comment]
Added interface design

**Comment by denizturkcapar** [comment]
Sarika and I did a UML diagram first in order to get a good picture of how our design documentation should look. Did research on how spellchecking systems work in general and thought about how we could translate these ideas to the spellcheck application for this project in the context of redis, tries and other teams.

Then I put our ideas to the design documentation in detail. I researched the structure of design documentations. I also detailed how each function worked and why they are important for the spellcheck utility. I wrote the purpose of the spellcheck application and explained how the two main modes (interactive and batch) are different from each other and how the requirements change for different modes.
